In [1]:
import pandas as pd

In [2]:
DATA_PATH = "../data/raw/en_fr.parquet"

In [3]:
df = pd.read_parquet(DATA_PATH)
df.head()

  id                                        translation
0  0  {'en': 'The Wanderer', 'fr': 'Le grand Meaulnes'}
1  1   {'en': 'Alain-Fournier', 'fr': 'Alain-Fournier'}
2  2      {'en': 'First Part', 'fr': 'PREMIÈRE PARTIE'}
3  3              {'en': 'I', 'fr': 'CHAPITRE PREMIER'}
4  4     {'en': 'THE BOARDER', 'fr': 'LE PENSIONNAIRE'}

In [4]:
df["en"] = df["translation"].apply(lambda x: x["en"])
df["fr"] = df["translation"].apply(lambda x: x["fr"])

df = df[["en", "fr"]]
df.head()

               en                 fr
0    The Wanderer  Le grand Meaulnes
1  Alain-Fournier     Alain-Fournier
2      First Part    PREMIÈRE PARTIE
3               I   CHAPITRE PREMIER
4     THE BOARDER    LE PENSIONNAIRE

In [5]:
from sklearn.model_selection import train_test_split

train_df, temp_df = train_test_split(
    df,
    test_size=0.2,
    random_state=42
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.5,
    random_state=42
)

In [6]:
train_df.to_parquet("../data/raw/train.parquet", index=False)
val_df.to_parquet("../data/raw/val.parquet", index=False)
test_df.to_parquet("../data/raw/test.parquet", index=False)

In [7]:
train_df.shape, val_df.shape, test_df.shape

((101668, 2), (12708, 2), (12709, 2))

In [8]:
train_df = pd.read_parquet("../data/raw/train.parquet")
train_df.head()

,en,fr
0,"The truth is, he ought to have been trusted wi...","La vérité est que j'eusse dû lui confier tout,..."
1,"To absorb it, we would need to fill containers...","Pour l'absorber, il eût fallu remplir des réci..."
2,"""Ah, that’s quite another thing; but promise m...",-- Alors c'est autre chose; mais promettez-moi...
3,"""Now for the lad; look sharp.""","Au mioche maintenant, dépechons!"
4,'I would give my life a thousand times to know...,– Je donnerais mille fois ma vie pour savoir c...

In [9]:
from machine_translation.tokenization import load_tokenizer
from machine_translation.config import load_tokenizer_config, load_data_config

In [10]:
TOKENIZER_PATH = "../artifacts/tokenizer/tokenizer.json"
TOKENIZER_CONFIG_PATH = "../configs/tokenizers/shared_unigram.yaml"
DATA_CONFIG_PATH = "../configs/data/default.yaml"
tokenizer_config = load_tokenizer_config(TOKENIZER_CONFIG_PATH)
data_config = load_data_config(DATA_CONFIG_PATH)

In [11]:
tokenizer = load_tokenizer(TOKENIZER_PATH, tokenizer_config.special_tokens)
tokenizer

Tokenizer(version="1.0", truncation=None, padding=None, added_tokens=[{"id":0, "content":"<pad>", "single_word":False, "lstrip":False, "rstrip":False, "normalized":False, "special":True}, {"id":1, "content":"<unk>", "single_word":False, "lstrip":False, "rstrip":False, "normalized":False, "special":True}, {"id":2, "content":"<bos>", "single_word":False, "lstrip":False, "rstrip":False, "normalized":False, "special":True}, {"id":3, "content":"<eos>", "single_word":False, "lstrip":False, "rstrip":False, "normalized":False, "special":True}], normalizer=NFKC(), pre_tokenizer=Metaspace(replacement="▁", prepend_scheme=always, split=True), post_processor=TemplateProcessing(single=[SpecialToken(id="<bos>", type_id=0), Sequence(id=A, type_id=0), SpecialToken(id="<eos>", type_id=0)], pair=[Sequence(id=A, type_id=0), Sequence(id=B, type_id=1)], special_tokens={"<bos>":SpecialToken(id="<bos>", ids=[2], tokens=["<bos>"]), "<eos>":SpecialToken(id="<eos>", ids=[3], tokens=["<eos>"])}), decoder=Metaspace(replacement="▁", prepend_scheme=always, split=True), model=Unigram(unk_id=1, vocab=[("<pad>", 0), ("<unk>", 0), ("<bos>", 0), ("<eos>", 0), (",", -3.039099507914935), (".", -3.701928324487948), ("▁the", -3.82052181426182), ("▁de", -4.067391329041259), ("s", -4.076178046514061), ("▁of", -4.460129432052954), ("▁to", -4.476826104433302), ("▁a", -4.501038716897961), ("▁and", -4.5735140943476615), ("▁la", -4.662156089069766), ("▁et", -4.720722036734992), ("▁", -4.791123531324661), ("▁le", -4.866116769250549), (";", -4.987091685980273), ("▁in", -5.024485073512942), ("▁à", -5.042408656199177), ("▁I", -5.056116771836194), ("e", -5.076353483503027), ("▁que", -5.210416819397711), ("▁was", -5.215495292702519), ("▁les", -5.304621832003065), ("▁that", -5.327431709330064), ("▁he", -5.44164086845946), ("▁un", -5.464170033691639), ("▁en", -5.56619698295907), ("▁his", -5.568400809683068), ("▁had", -5.600206911692705), ("t", -5.609292085850319), ("▁me", -5.611268689677573), ("▁je", -5.644871007311149), ("▁il", -5.6880547619970905), ("▁qui", -5.689315151684758), ("▁with", -5.693385626002126), ("▁ne", -5.721819684476264), ("!", -5.734162699039395), ("▁it", -5.752491096669306), ("▁se", -5.783029508374771), ("▁on", -5.811521864106576), ("▁une", -5.815105240940653), ("▁dans", -5.846853774934955), ("▁you", -5.850684591077437), ("s,", -5.855236036607742), ("▁pas", -5.860680758270686), ("▁des", -5.864819665488691), ("▁du", -5.8689972401202475), ("▁for", -5.878419139763091), ("▁not", -5.900771388007959), ("▁her", -5.911673202511725), ("ing", -5.922232242288688), ("ed", -5.923589218973097), ("▁at", -5.925525942896968), ("y", -5.928927743672661), ("▁as", -5.96398246093632), ("r", -5.966371044500502), ("▁ce", -6.031826935185636), ("▁pour", -6.032294114623394), ("?", -6.045409809743548), ("▁vous", -6.048192113877816), ("▁which", -6.073961578458482), ("a", -6.076392323215442), ("▁my", -6.086904098037422), (":", -6.099328457377215), ("▁be", -6.107689206869093), ("d", -6.109794110943982), ("▁is", -6.122395504037286), ("▁--", -6.159890394564227), ("▁son", -6.169926825304447), ("▁sur", -6.186352508543784), ("▁have", -6.247600827964433), ("▁she", -6.247663331315749), ("▁plus", -6.260947496051674), ("."", -6.277497945968008), ("▁lui", -6.290174848980518), ("▁au", -6.297073919259994), ("▁by", -6.298258159038459), ("▁sa", -6.314041133743293), ("▁this", -6.3271169161370295), ("▁par", -6.334439438237872), ("er", -6.354324094591057), ("é", -6.379855219323687), ("l", -6.410133599205295), ("▁était", -6.430563071375023), ("▁but", -6.434055144056947), ("▁all", -6.4389279311871075), ("▁avait", -6.441364843918896), ("▁avec", -6.446405904438359), ("▁from", -6.452842203797726), ("▁The", -6.455707756230401), ("▁him", -6.465281384113558), ("▁nous", -6.479157025683488), ("n", -6.495753297260563), ("▁were", -6.504252720324006), ("ait", -6.5101928046731405), ("▁so", -6.519374864154424), ("▁Il", -6.520058212282315), ...], byte_fallback=False))

In [12]:
sample = "Before we start, let's make sure we have the right tools for the job."

encoded_sample = tokenizer.encode(sample)
print("Encoded sample:", encoded_sample)
print("Encoded sample:", encoded_sample.ids)
print("Decoded sample:", tokenizer.decode(encoded_sample.ids))
print("Tokens:", encoded_sample.tokens)

Encoded sample: Encoding(num_tokens=21, attributes=[ids, type_ids, tokens, offsets, attention_mask, special_tokens_mask, overflowing])
Encoded sample: [2, 6310, 127, 3328, 4, 598, 115, 293, 1026, 127, 72, 6, 605, 6457, 49, 6, 1503, 120, 157, 5, 3]
Decoded sample: Before we start, let's make sure we have the right tools for the job.
Tokens: ['<bos>', '▁Before', '▁we', '▁start', ',', '▁let', "'s", '▁make', '▁sure', '▁we', '▁have', '▁the', '▁right', '▁tools', '▁for', '▁the', '▁j', 'o', 'b', '.', '<eos>']

In [13]:
from machine_translation import get_data_loaders

In [17]:
train_loader, validation_loader, test_loader = get_data_loaders(
    tokenizer=tokenizer,
    data_config=data_config,
    tokenizer_config=tokenizer_config,
)

In [19]:
len(train_loader), len(validation_loader), len(test_loader)

In [ ]:
for batch in train_loader:
    print(batch["source_ids"])
    print(batch["target_ids"])
    print(batch["source_padding_mask"])
    print(batch["target_padding_mask"])
    print("Source input IDs shape:", batch["source_ids"].shape)
    print("Target input IDs shape:", batch["target_ids"].shape)
    print("Source padding mask shape:", batch["source_padding_mask"].shape)
    print("Target padding mask shape:", batch["target_padding_mask"].shape)
    break